### PR TITLE
Add secret key in the admin settings

### PR DESCRIPTION
**Pull request by gustavobazzo**

### CODE REVIEW

**Comment by timhunt** [comment]
Thanks for this. It is a useful addition.

However, we need some improvements to the code, before it is ready to be merged:

# Please don't change the version number in your pull request. I will increase the version number when it is time to do a release.
# In is_authorized_secret_token, I think it would be better for performance to have get_config('filter_embedquestion', 'secret') first in the array, rather than last.
# The comment "// autorized secret history." has several mistakes.
# Please add some unit tests for is_authorized_secret_token.
# I think that in an ideal world, the admin setting would be protected by something like admin_setting_configpasswordunmask or admin_setting_encryptedpassword, but both of those only do simple text inputs, not textareas, and we need a text area. I guess it is not worth worrying about this for now.
# I think that some of the Automated check failures are caused by recent changes in Moodle core, not your change. Sorry about that, I will try to fix that soon. However, please ensure that your change does not make it worse.

**Comment by timhunt** [comment]
Oh! you had made some additional changes. Sorry. I did not notice until now. Always a good idea to comment about what you are doing.

I am just trying to fix this pugin to work with Moodle 4.0. I will review your changes once I have done that.

**Comment by gustavobazzo** [comment]
Alright Tim, thank you.

**Comment by timhunt** [comment]
Thanks. Merged now.

**Pull request merged**
